### PR TITLE
Split interface files

### PR DESCRIPTION
**Pull request by jonathanKingston**
**Reviewer:** 
**Asana:**

### CODE REVIEW

**Comment by shakyShane** [comment]
@jonathanKingston When I focus into a field (with your changes) I get the following error in safari

image

**Comment by GioSensation** [comment]
@shakyShane We don't support Safari at all, so you can ignore that.

**Comment by shakyShane** [comment]
@GioSensation sorry, I meant our macOS browser :)

**Comment by jonathanKingston** [comment]
Rebased over your latest PR, I don't think I lost any changes in src/DeviceInterface.js as you were just rebasing on mine and without changes.

**Pull request closed without merging**
